In [1]:
import torch
print(torch.__version__)

1.6.0


### 自动求导机制

In [3]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[ 1.2551],
        [ 1.0040],
        [-1.2125],
        [ 1.3900]], requires_grad=True)
tensor([[-0.0294],
        [-1.0484],
        [-0.2884],
        [ 0.5163]], requires_grad=True)
tensor([[ 0.5305, -0.0443, -1.5247,  1.3890],
        [-0.4840, -1.2439, -0.5127,  0.6231],
        [-0.8703,  0.0654,  0.5735, -0.1244],
        [-1.3704,  0.9178, -0.0209,  0.4482]])


In [4]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[2.6649]], grad_fn=<MmBackward>)


In [5]:
z = x.t().mm(W).mm(y).abs()
print(z)

tensor([[2.6649]], grad_fn=<AbsBackward>)


In [6]:
print(x.grad)

None


In [7]:
z.backward()

In [8]:
print(x.grad)

tensor([[ 1.1877],
        [ 1.7880],
        [-0.2726],
        [-0.6845]])


In [9]:
print(W.mm(y))

tensor([[ 1.1877],
        [ 1.7880],
        [-0.2726],
        [-0.6845]], grad_fn=<MmBackward>)


### 默认情况下，定义的tensor属性requires_grad为false

In [ ]:
x = torch.randn(4,1)
print(x)
y = torch.mm(torch.t(x),x)
y.backward()

In [ ]:
print(y)

print(x.grad)

print(2*x)

### PyTorch Tensor 与 Numpy 转换

In [ ]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

In [ ]:
a_tensor = torch.from_numpy(a)
print(a_tensor)
print(type(a_tensor))

In [ ]:
b = a_tensor.numpy()
print(b)
print(type(b))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))